/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "agenda.h"


void
agenda_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	char *inicializar_1_arg;
	int  *result_2;
	registro  insere_1_arg;
	int  *result_3;
	registro  remove_1_arg;
	registro  *result_4;
	char * busca_1_arg;
	int  *result_5;
	struct registro  altera_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, AGENDA, AGENDAVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = inicializar_1((void*)&inicializar_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = insere_1(&insere_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = remove_1(&remove_1_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = busca_1(&busca_1_arg, clnt);
	if (result_4 == (registro *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = altera_1(&altera_1_arg, clnt);
	if (result_5 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	agenda_1 (host);
exit (0);
}
